### ISSUE TITLE
Hi neurobin,

### ISSUE THREAD

**Issue by danjde** [neurobin/JLIVECD#15]
Hi neurobin,
I'm trying to create a Ubuntu Xenial custom live Linux,
but using this Ubuntu version and your last JLIVECD seem impossible to create a bootable live linux distro.
For the truth I've try only with usb pen (iso to usb with many different transfer tools).
Do you now issue about this?

many thanks

davide

**Comment by neurobin** [comment]
I heven't tested the latest version of JLIVECD with anything yet...

**Comment by danjde** [comment]
Hello.
I find how to resolve this issue.

Need to install syslinux-utils and run in terminal $ sudo isohybrid /path/to/custom_iso.iso
But this solution I don't know if work for UEFI mode.

Maybe this information can help you for update JLIVECD script.

PS
I've tested not only the last final JLIVECD version but the last 3 version, and not only with Xenial but with Trusty too. The behaviour, on my environment is the same.

**Comment by neurobin** [comment]
Updated the script. Previously the hybrid image option was only correct for UEFI mode. It's fixed now. You should be able to create hybrid image without UEFI, i.e give 'y' when asked for hybrid image, and 'n' when asked for 'UEFI' image.

**Comment by danjde** [comment]
Ok, perfect!
Just out of curiosity, 

Hybrid= for usb boot from old computer
UEFI= for usb boot from newer computer

is it correct?

many thanks! :-)

**Comment by neurobin** [comment]
Hybrid only = for legacy boot
Hybrid + UEFI = For UEFI boot (it generally comes with newer computers)
