### ISSUE TITLE
Dynamic image name and self uninstaller

### ISSUE THREAD

**Issue by danjde** [neurobin/JLIVECD#16]
Hi neurobin,
I've tested your new release and now hybrid and UEFI works fine.
I suggest you two things, if you like:

1) at the end of the work give automatically a name based from two mix: release name, and day-month-year-hour, with the ability to insert changes in the name
2) including on the install script the ability to remove all previous JL installed versions directory. So because the new one is different and I've run the installer without removing manually the previous and this has generate some trouble..

for the rest, for me, JL is a very very good software (more fine of Cubic because more essential and to this doesn't miss a beat. I've try Cubic recently and it has created several problems to me, because it automates too ) ;-)

Thanks!

**Comment by neurobin** [comment]
In new version:

1.  You can use the `config.conf` file in your project directory to do that. For example, An entry `DISKNAME=name-$(date -u |tr ' ' '-')` will give you something like `name-Tue-Mar-28-16:53:08-UTC-2017`. **Note:** this files is essentially a Bash script, so use with care.
2. `jlopt -u` will uninstall JLiveCD itself
