### ISSUE TITLE
Problem with the Desktop file

### ISSUE THREAD

**Issue by ikeman32** [neurobin/JLIVECD#18]
This is a small matter, the script works like a charm from the command line. But the desktop entry file appears to be invalid. When I click the menu launcher this is what comes up:

An error window that says: Invalid desktop entry file: '/home/duke/.local/share/applications/JLIVECD.desktop'

The only other problem which was easily corrected is that the script seems to have a problem with the terminal emulator call Terminator when opening the chroot terminal. I set the system so that it would open xterm instead.

I am using Lubuntu 17.04 amd64 and other than what I stated above it works like a charm. Have successfully used it to remaster the Lubuntu iso.

**Comment by neurobin** [comment]
I am not sure how it got into '/home/duke/.local/share/applications/JLIVECD.desktop'. the install script installs the desktop entry file in '/usr/share/applications/JLIVECD.desktop'. May be deleting '/home/duke/.local/share/applications/JLIVECD.desktop' would help.

> I set the system so that it would open xterm instead

I am not sure if you mean the system default terminal, but if it is, you don't need to change the system terminal, you can just change JLIVECD default terminal:

```bash
sudo JLopt -t1 xterm
```

**Comment by ikeman32** [comment]
I got the issue worked out. Apparently the install script creates the desktop Exec entry with quotes around the launch command. Removing the quotes got the launcher working properly. All is well.
