### ISSUE TITLE
File path issues

### ISSUE THREAD

**Issue by jemdem** [neurobin/JLIVECD#2]
JLIVECD seems to have a hard interpreting paths.

It can't read "~/", I have to enter the full path.
It can't read "\", I have to enter only paths that do not contains any spacing.

**Comment by neurobin** [comment]
thanks for the feedback i will review it...

**Comment by neurobin** [comment]
Just updated a new version. You can use ~/ and spaces now. But spaces are not allowed in project path (only in iso path) because of future conflict.....

Don't use quotes in path.....ex:
path: "~/Downloads"              //incorrect
path: ~/Downloads                 //correct

**Comment by neurobin** [comment]
There were still some bugs, it's fixed now...
