### ISSUE TITLE
[question] Can I setup default user password?

### ISSUE THREAD

**Issue by ghost** [neurobin/JLIVECD#23]
I hope setup default user(mint) password.
In chrooted terminal
```
# adduser mint
```
Setup password during this process.
And exit chrooted terminal, then rebuild squashfs -> create iso.
Launch created iso, unfortunately, I can't log in Desktop.
Maybe, this behavior reason is JLIVECD does remove `/home/mint` directory.
I hope just boot up a custom live system, simply ssh by another machine with password authentication.

**Comment by neurobin** [comment]
You can do **anything**. But you need to know how. For starters, deleting the home dir is the default, but you can prevent it. There is an option that asks for whether to retain home dir or you can set `RETAINHOME=y` in `config.conf` to keep the home dir intact.

```

*** ##### Init script & Kernel related #####
Rebuild the initramfs if you have 
1. changed init scripts or kernel modules
2. installed new kernel and want to boot that kernel in the live session.

=== Rebuild initramfs (Y/n)? (default 'n'): 

=== Retain home directory (Y/n)? (default 'n'): 

```

**Comment by ghost** [comment]
@neurobin 
I'm sorry I understand it !!
Thank you for very much!!
I'll try it.
