### ISSUE TITLE
Does it work with Manjaro XFCE?

### ISSUE THREAD

**Issue by DwarfFighterCleric** [neurobin/JLIVECD#26]
Hello, after years using JLiveCD to make custom Xubuntu ISO's, I tried using it today to create a custom Manjaro ISO.
It said "Could not open mnt/arch/x86_64/airootfs.sfs", I renamed it from "rootfs.sfs" to "airoot" and then it was able to initialize the chroot but with a bunch of errors. Xterm popped up but I suspect it was browsing from my "host" machine, there were packages already installed that do not come by default for example, no home directory, no "mydir" directory.  
Is the Manjaro filesystem different compared to "standard Arch"? (I've never used it)  
PICTURES: [imgur.com/a/yVuWZHL](https://imgur.com/a/yVuWZHL)

**Comment by neurobin** [comment]
Arch is supported but Manjaro is not. Manjaro makes there ISOs differently than standard Arch. I am using Manjaro now, so it may come in some future version, but it may take a while.

One possible workaround could be like this:

Use official Arch ISO, use JLIVECD to modify it and turn it into manjaro. This should give you a modified Arch ISO which contains Manjaro.
