### ISSUE TITLE
Customizing Linux Mint LiveCD

### ISSUE THREAD

**Issue by KaptanOmer** [neurobin/JLIVECD#3]
Hello. I want to customize Linux Mint LiveCD/USB. But I'm a novice at Linux terminal commands. 
The changes I want to make is listed below (in order of "System Settings")

1- application appearance (kFaenza icon set will be installed)
2- locale (Turkish will be installed) [this is optional]
3- workspace appearance (window decoration, cursor theme, desktop theme and splash screen will be changed)
4- input devices (keyboard layout will be changed into Turkish) [this must be changed]
5- pre-installed software will be updated
6- adblock extension for mozilla firefox will be installed
7- Google chrome will be installed (with adblock extension)
8- GRUB customizer will be installed

that's all. I won't share my customized linux mint. It's just for personal use. I read your tutorial here: http://community.linuxmint.com/tutorial/view/1784
But I couldn't do it. So I tried the alternative JLIVECD@neurobin. Here is what I did:

I copy/paste this code on terminal
sudo apt-get install squashfs-tools genisoimage
then I downloaded tar.gz archive then extracted. Then run the following command

/home/kaptan/JLIVECD-release/install.sh
password for kaptan:
..... Install Complete!
..... see the readme file provided with this software for instructions to use it...

After installation. I click on JLIVECD application shortcut and get this error:

There was an error launching the application.
Detail: Failed to execute child process "xterm" (No such file or directory)

How can I do what I want, What codes do I need?

If making these changes is possible just using chroot terminal, what codes do I need?

**Comment by KaptanOmer** [comment]
I forgot but The Linux Mint 17.2 KDE version will be used in the process.

**Comment by neurobin** [comment]
That's odd..., probably your x-terminal-emulator link is broken.
Run this command in terminal:

```
sudo update-alternatives --config x-terminal-emulator 
```

and choose a terminal from the list. If you don't have a suitable terminal installed, you can install a terminal like gnome-terminal or xterm.

```
sudo apt-get install gnome-terminal
sudo apt-get install xterm
```

And give me some info, like what OS you are using and what Desktop Environment.. i.e your host environment.

**Comment by neurobin** [comment]
In chroot to update system:

```
sudo apt-get update
sudo apt-get upgrade
```

You can also get builtin help from JLiveCD, run (in chroot):

```
cat help
```

to see commonly used commands.

If you are able to go into chroot, let me know. I will give instructions for other scenario too.

**Comment by KaptanOmer** [comment]
sudo update-alternatives --config x-terminal-emulator 
says "There is only one alternative in link group x-terminl-emulator (providing /usr/bin/x-terminal-emulator): /usr/bin/mate-terminal"
Nothing to configure

So I installed xterm.

My system is Linux Mint MATE 64bit. (kernel: 3.16.0-38-generic --> Cinnamon version 2.6.13) (later, I installed cinnamon desktop environment and now cinnamon is default. But in System info it still shows "Linux Mint MATE 64bit")

**Comment by KaptanOmer** [comment]
the program started. it is doing some things automatically. it is now creating new filesystem.squashfs. it is taking long. After some time. it showed a message: Congrats! Customized cd/dvd creation completed. press enter to exit
OMG. I didn't customize anything :)

**Comment by neurobin** [comment]
It seems x-terminal-emulator didn't run properly. mate-terminal seems to have a serious bug regarding this issue: https://github.com/mate-desktop/mate-panel/issues/57
and https://bugs.launchpad.net/ubuntu-mate/+bug/1415048

Try this to fix that:

```
sudo ln -s mate-terminal /usr/bin/xterm
sudo ln -sf /usr/bin/mate-terminal /etc/alternatives/x-terminal-emulator
sudo ln -sf /etc/alternatives/x-terminal-emulator /usr/bin/x-terminal-emulator
```

If that doesn't solve the problem, use gnome terminal:

```
sudo apt-get install gnome-terminal
sudo ln -sf /usr/bin/gnome-terminal /etc/alternatives/x-terminal-emulator
sudo ln -sf /etc/alternatives/x-terminal-emulator /usr/bin/x-terminal-emulator
```

**Comment by neurobin** [comment]
And when you run JLIVECD again, you don't need to put all the credentials again. When asked for fresh start, put `n` (for no), and then just hit enter on the subsequent prompts, it will take your previous choices automatically. The project is saved in the project directory and it won't create it twice. If your `x-terminal-emulator` link not broken then, it should create the chroot properly. Try running

```
x-terminal-emulator
```

in terminal (it would open a new terminal) to check if the link is working properly before running JLIVECD.

**Comment by KaptanOmer** [comment]
I tried the first solution. then I run JLIVECD again, pressed enter-enter-enter. no change... it rebuild squashfile itself and closed terminal automatically. I guess, I won't be able to achieve it. It will stay as a dream for me. Thanks for your interest.

**Comment by neurobin** [comment]
Have you checked if x-terminal-emulator is working properly, before running JLIVECD?
the command:

```
x-terminal-emulator
```

should open a new terminal on top of the current terminal.

**Comment by neurobin** [comment]
I have found a bug that might lead to not initializing the chroot terminal. Check out my latest update.

**Comment by neurobin** [comment]
It can now use `xterm` if `x-terminal-emulator` fails. I think your problem should be solved now....
