### ISSUE TITLE
Ubiquity hang during harddisk detection

### ISSUE THREAD

**Issue by danjde** [neurobin/JLIVECD#6]
Hi neurobin,
I've found that on a live system based to Ubuntu-Gnome 14.04 upgraded to the last packages and Gnome 3.12.2, Ubiquity freeze/hang during harddisk detection.

For bypass the problem, is relatively simple:

must substitute

```
sh -c 'ubiquity gtk_ui'
```

with

```
sh -c 'sudo ubiquity gtk_ui'
```

on /usr/share/applications/ubiquity-gtkui.desktop

**Comment by neurobin** [comment]
I have to say, you have a great skill of excavation and patience...
thanks a lot...
I will add it to the bugs section in my tutorial...:D

**Comment by neurobin** [comment]
Hey, I have a proposal, Fork my repository, and add the bug and solution in the readme file and make a pull request. This way I can add you as a contributor of this project..
What do you say..?

**Comment by danjde** [comment]
Hi neurobin
I think it be possible and I appreciate your offer.
Could you explain better what I shoud do for JLivecd project?

You should know that I've not so much time but for example I could reply to
users for questione concerning live creation process and eventually bug
solution...

Many thanks!
Il 11/ott/2015 18:36, "Jahidul Hamid" notifications@github.com ha scritto:

**Comment by neurobin** [comment]
Thanks for your interest..
Visiting the project page: https://github.com/neurobin/JLIVECD

you can see three buttons at top right (Watching/unwatch), (star/unstar), (Fork)

Watching: If you click it and watch the project, you will be notified about every changes and bug reports.

star/unstar: Like button.

Fork: Click this button and fork i.e preserve a copy of this project in your own github repo. Then click on the readme.md file. Click on the pen icon i.e edit this readme.md file and add the ubiquity bug and solution in the additional info section (at 5). Then save the file. then make a pull request. When I accept the pull request you will be added as a contributor of the project automatically.
