### ISSUE TITLE
Error with Ubuntu-Mate 15.10

### ISSUE THREAD

**Issue by spsf64** [neurobin/JLIVECD#8]
Chroot fail and xterm error (which is installed)
Terminal output:

......Found: initrd.lz

......Preparing network connection for chroot.....

......Network connection will be available in chroot.....

......Debcache Management starting....
......moving deb files to edit/var/cache/apt/archives......

......Preparing the chroot terminal......
access control disabled, clients can connect from any host
------Preparing chroot failed-----

......Preparation complete! Running chroot terminal...
......When you are finished, run: exit or simply close the chroot terminal.....

...... run 'cat help' or './help' to get help in chroot terminal......

......Failed to run x-terminal-emulator. Check if x-terminal-emulator link exists and not broken
Want to continue without chroot (Y/n)?: 
......Running x-terminal-emulator failed. Exiting...

**Comment by neurobin** [comment]
Can you run the command `x-terminal-emulator` in a terminal and check if this link is not broken or something....

You can also apply a patch in JLIVECD to forcefully use your desired terminal application for chroot. Run this command in a terminal to apply the patch:

```
sudo sed -i 's/x-terminal-emulator/mate-terminal/g' /usr/local/JLIVECD/main/custom_desktop
```

This will force Jlivecd to use `mate-terminal` for chroot.

**Comment by spsf64** [comment]
x-terminal-emulator is working fine, used the sed command and still get the same output: "Preparing chroot failed"

**Comment by neurobin** [comment]
As you have xterm installed, how about using xterm, then:

```
sudo sed -i 's/mate-terminal/xterm/g' /usr/local/JLIVECD/main/custom_desktop
```

**Comment by spsf64** [comment]
Thanks neurobin! With the latest command it works now!
Maybe you could add this info to the readme?!
Regards

**Comment by neurobin** [comment]
I have pushed a new commit. The updated version tries for `xterm` if `x-terminal-emulator` fails automatically.

**Comment by spsf64** [comment]
Thank you!

**Comment by neurobin** [comment]
I have pushed a new commit which tries `xterm` automatically if `x-terminal-emulator` fails. And also the docs been updated.
Regards, Jahid.
